//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.MulticastDownloader.Core.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MS.MulticastDownloader.Core.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block size must be multiple of 8..
        /// </summary>
        internal static string BlockSizeMustBeMultipleOf8 {
            get {
                return ResourceManager.GetString("BlockSizeMustBeMultipleOf8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate does not contain a valid public or private key. Check your asymmetric key flags..
        /// </summary>
        internal static string CertificateDoesNotContainPrivateKey {
            get {
                return ResourceManager.GetString("CertificateDoesNotContainPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate file type mismatch. Expected a PEM-encoded file containing an RSA key pair..
        /// </summary>
        internal static string CertificateTypeMismatch {
            get {
                return ResourceManager.GetString("CertificateTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP client not initialized..
        /// </summary>
        internal static string ClientNotInitialized {
            get {
                return ResourceManager.GetString("ClientNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed: check the connection URI and verify your encoding parameters..
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate file entry in table..
        /// </summary>
        internal static string DuplicateFile {
            get {
                return ResourceManager.GetString("DuplicateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid certificate file..
        /// </summary>
        internal static string InvalidCertificateFile {
            get {
                return ResourceManager.GetString("InvalidCertificateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid encoder object..
        /// </summary>
        internal static string InvalidEncoder {
            get {
                return ResourceManager.GetString("InvalidEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key file..
        /// </summary>
        internal static string InvalidKeyFile {
            get {
                return ResourceManager.GetString("InvalidKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server certificate was invalid..
        /// </summary>
        internal static string InvalidServerCertificate {
            get {
                return ResourceManager.GetString("InvalidServerCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URI scheme..
        /// </summary>
        internal static string InvalidUriScheme {
            get {
                return ResourceManager.GetString("InvalidUriScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multicast download failed..
        /// </summary>
        internal static string MulticastDownloadFailed {
            get {
                return ResourceManager.GetString("MulticastDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a valid encoder when using TLS..
        /// </summary>
        internal static string MustSpecifyEncoder {
            get {
                return ResourceManager.GetString("MustSpecifyEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed..
        /// </summary>
        internal static string RequestFailed {
            get {
                return ResourceManager.GetString("RequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server payload mismatch..
        /// </summary>
        internal static string ServerPayloadMismatch {
            get {
                return ResourceManager.GetString("ServerPayloadMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session aborted..
        /// </summary>
        internal static string SessionAborted {
            get {
                return ResourceManager.GetString("SessionAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status update failed..
        /// </summary>
        internal static string StatusUpdateFailed {
            get {
                return ResourceManager.GetString("StatusUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String cannot be null or empty..
        /// </summary>
        internal static string StringCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("StringCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP download failed..
        /// </summary>
        internal static string TcpDownloadFailed {
            get {
                return ResourceManager.GetString("TcpDownloadFailed", resourceCulture);
            }
        }
    }
}
