//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.MulticastDownloader.Core.Server.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MS.MulticastDownloader.Core.Server.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to add a duplicate connection to the server..
        /// </summary>
        internal static string AttemptToAddDuplicateConnection {
            get {
                return ResourceManager.GetString("AttemptToAddDuplicateConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed..
        /// </summary>
        internal static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate type mismatch: expected a private key file..
        /// </summary>
        internal static string CertificateTypeMismatch {
            get {
                return ResourceManager.GetString("CertificateTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the specified interface on this server..
        /// </summary>
        internal static string CouldNotFindInterface {
            get {
                return ResourceManager.GetString("CouldNotFindInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid multicast burst length..
        /// </summary>
        internal static string InvalidMulticastBurstLength {
            get {
                return ResourceManager.GetString("InvalidMulticastBurstLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPV6 multicast addresses are not currently supported..
        /// </summary>
        internal static string Ipv6MulticastNotSupported {
            get {
                return ResourceManager.GetString("Ipv6MulticastNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum connections too low..
        /// </summary>
        internal static string MaxConnectionsTooLow {
            get {
                return ResourceManager.GetString("MaxConnectionsTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum sessions too low..
        /// </summary>
        internal static string MaxSessionsTooLow {
            get {
                return ResourceManager.GetString("MaxSessionsTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTU must be at least 576..
        /// </summary>
        internal static string MtuTooLow {
            get {
                return ResourceManager.GetString("MtuTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify at least 10 megabits per second as the upper limit..
        /// </summary>
        internal static string MustSpecifyAtLeast10MbitASecond {
            get {
                return ResourceManager.GetString("MustSpecifyAtLeast10MbitASecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify an encoder when using TLS..
        /// </summary>
        internal static string MustSpecifyEncoder {
            get {
                return ResourceManager.GetString("MustSpecifyEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a multicast address and start port..
        /// </summary>
        internal static string MustSpecifyMulticastAddressAndStartPort {
            get {
                return ResourceManager.GetString("MustSpecifyMulticastAddressAndStartPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server session aborted..
        /// </summary>
        internal static string ServerAborted {
            get {
                return ResourceManager.GetString("ServerAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many connections active..
        /// </summary>
        internal static string TooManyConnections {
            get {
                return ResourceManager.GetString("TooManyConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many sessions active..
        /// </summary>
        internal static string TooManySessions {
            get {
                return ResourceManager.GetString("TooManySessions", resourceCulture);
            }
        }
    }
}
